vscode:
  extensions:
    - asciidoctor.asciidoctor-vscode
    - hediet.vscode-drawio
    - jebbs.plantuml
tasks:
  - name: Start web server
    openMode: tab-after
    init: python -m http.server 8000

ports:
  - port: 8000
    onOpen: open-preview